version_info: "0"
- '@type': type.googleapis.com/envoy.api.v3.Listener
  name: listener_0
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  filter_chains:
    - filters:
        - name: envoy.http_connection_manager
          config:
            stat_prefix: ingress_https
            codec_type: AUTO
            server_name: default
            rds:
              route_config_name: local_route
              config_source:
                path: /etc/envoy/dynamic/rds.yaml
            http_filters:
              - name: envoy.router
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/etc/envoy/server.pem"
              private_key:
                filename: "/etc/envoy/server.key"