version_info: "0"
resources:
- '@type': type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_0
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  filter_chains:
    - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_https
            codec_type: AUTO
            server_name: default
            rds:
              route_config_name: local_route
              config_source:
                path_config_source:
                  path: /etc/envoy/dynamic/rds.yaml
                resource_api_version: v3
            http_filters:
              - name: envoy.router
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/etc/envoy/server.pem"
              private_key:
                filename: "/etc/envoy/server.key"