apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.overlay
spec:
  insecureSkipTLSVerify: true
  group: overlay
  groupPriorityMinimum: 1
  versionPriority: 1
  service:
    name: external-crd
    namespace: external-crd-system
  version: v1alpha1
